version: '3.9'
services:
  models-bee-detector:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      ddtrace-run python3 /app/server.py
    environment:
      - ENV_ID=dev
      - DD_SERVICE=models-bee-detector
      - DD_ENV=dev
      - DD_PROFILING_ENABLED=true
    ports:
      - 8700:8700
      - 8126:8126
    volumes:
      - .:/app/
    restart: always
    network_mode: bridge
    networks:
      - gratheon
networks:
  gratheon:
