blank_issues_enabled: true
contact_links:
  - name: ðŸ“„ Docs
    url: https://docs.ultralytics.com/yolov5
    about: View Ultralytics YOLOv5 Docs
  - name: ðŸ’¬ Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: ðŸŽ§ Discord
    url: https://discord.gg/7aegy5d8
    about: Ask on Ultralytics Discord
