version: "3.9"
services:
  generate_trt:
    build:
      context: .
      dockerfile: ./x86.dockerfile
    volumes:
      - ./data/allImages_1024_catheter_yolo/images:/app/images
      - ./trained-inference-models/:/app/trained-inference-models/
      - ./outputs/:/app/outputs/
      - ./build_engine.sh:/app/build_engine.sh
      - ./infer_trt.py:/app/infer_trt.py
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    command: bash /app/build_engine.sh
