# Ultralytics YOLO ðŸš€, AGPL-3.0 license
# YOLO Continuous Integration (CI) GitHub Actions tests

name: Check Broken links

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # runs at 00:00 UTC every day

jobs:
  Links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Markdown and HTML links
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          fail: true
          # accept 429(Instagram, 'too many requests'), 999(LinkedIn, 'unknown status code'), Timeout(Twitter)
          args: --accept 429,999 --exclude-loopback --exclude twitter.com --exclude-path '**/ci-testing.yaml' --exclude-mail './**/*.md' './**/*.html'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Test Markdown, HTML, YAML, Python and Notebook links
        if: github.event_name == 'workflow_dispatch'
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          fail: true
          # accept 429(Instagram, 'too many requests'), 999(LinkedIn, 'unknown status code'), Timeout(Twitter)
          args: --accept 429,999 --exclude-loopback --exclude twitter.com,url.com --exclude-path '**/ci-testing.yaml' --exclude-mail './**/*.md' './**/*.html' './**/*.yml' './**/*.yaml' './**/*.py' './**/*.ipynb'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
