# YOLOv5 ğŸš€ by Ultralytics, GPL-3.0 license

name: Close stale issues
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            ğŸ‘‹ Hello, this issue has been automatically marked as stale because it has not had recent activity. Please note it will be closed if no further activity occurs.

            Access additional [YOLOv5](https://ultralytics.com/yolov5) ğŸš€ resources:
            - **Wiki** â€“ https://github.com/ultralytics/yolov5/wiki
            - **Tutorials** â€“ https://github.com/ultralytics/yolov5#tutorials
            - **Docs** â€“ https://docs.ultralytics.com

            Access additional [Ultralytics](https://ultralytics.com) âš¡ resources:
            - **Ultralytics HUB** â€“ https://ultralytics.com/hub
            - **Vision API** â€“ https://ultralytics.com/yolov5
            - **About Us** â€“ https://ultralytics.com/about
            - **Join Our Team** â€“ https://ultralytics.com/work
            - **Contact Us** â€“ https://ultralytics.com/contact

            Feel free to inform us of any other **issues** you discover or **feature requests** that come to mind in the future. Pull Requests (PRs) are also always welcomed!

            Thank you for your contributions to YOLOv5 ğŸš€ and Vision AI â­!

          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions YOLOv5 ğŸš€ and Vision AI â­.'
          days-before-issue-stale: 30
          days-before-issue-close: 10
          days-before-pr-stale: 90
          days-before-pr-close: 30
          exempt-issue-labels: 'documentation,tutorial,TODO'
          operations-per-run: 300  # The maximum number of operations per run, used to control rate limiting.
